# Generated by Django 4.2.6 on 2023-10-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_todotasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotasks',
            name='id',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
