# Generated by Django 4.2.6 on 2023-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_programused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programused',
            name='last_time_saved',
            field=models.DateTimeField(null=True),
        ),
    ]
